<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
	<OutputType>Exe</OutputType>
	<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonDiffPatch.Net" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\common\Entra.EventHandlers.TestData\Entra.EventHandlers.TestData.csproj" />
	<ProjectReference Include="..\Entra.EventHandlers.Abstractions\Entra.EventHandlers.Abstractions.csproj" />
  </ItemGroup>
	
</Project>