<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Entra.EventHandlers.Abstractions" Version="1.5.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

</Project>
