<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>true</IsPackable>

	 <!-- NuGet metadata -->
	<PackageId>Entra.EventHandlers</PackageId>
	<Version>1.3.3</Version>
	<Authors>Jakub Szubarga</Authors>
	<Company>Szubarga.NET Jakub Szubarga</Company>
	<Description>Core implementation library for Microsoft Entra External ID Authentication Event Handlers. Provides fluent response builders, handler base classes, validation, routing helpers, and extensibility points for building custom authentication flows.</Description>
	<PackageTags>entra;entra-id;microsoft-entra;microsoft-entra-id;external-id;authentication-events;event-handlers;identity;authentication;dotnet;dotnet-library;csharp;fluent-api</PackageTags>

	<RepositoryUrl>https://github.com/szubajak/entra-event-handlers</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageProjectUrl>https://github.com/szubajak/entra-event-handlers</PackageProjectUrl>

	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.NuGet.md</PackageReadmeFile>
	<PackageIcon>icon.png</PackageIcon>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>

	<PackageReleaseNotes>
	Initial public release of the core implementation for Microsoft Entra External ID Authentication Event Handlers.
	Includes fluent response builders, handler base classes, validation, and execution pipeline.
	</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<None Include="LICENSE" Pack="true" PackagePath="" />
	<None Include="LICENSE-COMMERCIAL.md" Pack="true" PackagePath="" />
	<None Include="README.NuGet.md" Pack="true" PackagePath="" />
	<None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\abstractions\Entra.EventHandlers.Abstractions\Entra.EventHandlers.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Pack'">
	<PackageReference Include="Entra.EventHandlers.Abstractions" Version="1.4.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
