<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsTestProject>true</IsTestProject>
	<IsPackable>false</IsPackable>
	<OutputType>Exe</OutputType>
	<IsTestingPlatformApplication>true</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entra.EventHandlers.Security.AzureFunctions\Entra.EventHandlers.Security.AzureFunctions.csproj" />
  </ItemGroup>

</Project>