<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspnetcore\Entra.EventHandlers.AspNetCore\Entra.EventHandlers.AspNetCore.csproj" />
    <ProjectReference Include="..\Sample.Common\Sample.Common.csproj" />
  </ItemGroup>

</Project>
