using System.Text.Json.Serialization;

namespace Entra.EventHandlers.Abstractions.Protocol.Otp;

/// <summary>
/// Represents the one‑time passcode (OTP) information included in
/// EmailOtpSend events sent by Microsoft Entra.
/// </summary>
/// <remarks>
/// The OTP context contains the identifier to which the one‑time code
/// will be delivered (such as an email address) and the actual OTP value
/// generated by Microsoft Entra.
///
/// This data is provided so that custom extensions can implement
/// auditing, logging, fraud detection, or custom delivery logic.
///
/// For details on the OTP send event payload, see:
/// https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-email-otp-send-data
/// </remarks>
public class OtpContext
{
    /// <summary>
    /// Gets the identifier associated with the OTP delivery target.
    /// For EmailOtpSend events, this is the email address to which
    /// the one‑time code will be sent.
    /// </summary>
    [JsonPropertyName("identifier")]
    public required string Identifier { get; init; }

    /// <summary>
    /// Gets the one‑time code generated by Microsoft Entra for the OTP
    /// send operation. This value is intended for delivery to the user
    /// and may be used for auditing or custom delivery scenarios.
    /// </summary>
    [JsonPropertyName("oneTimeCode")]
    public required string OneTimeCode { get; init; }
}
