using Entra.EventHandlers.Abstractions.Protocol;
using Entra.EventHandlers.Abstractions.Protocol.Otp;
using System.Text.Json.Serialization;

namespace Entra.EventHandlers.Abstractions.Events;

/// <summary>
/// Represents the EmailOtpSend event sent by Microsoft Entra
/// to a custom extension endpoint during an authentication flow.
///
/// This type provides a strongly typed model for the incoming JSON payload.
/// It mirrors the public contract defined by Microsoft and contains no
/// additional logic.
/// </summary>
/// <remarks>
/// The EmailOtpSend event is triggered when Microsoft Entra generates
/// a one‑time passcode (OTP) intended for delivery to the user. Custom
/// extensions may use this event for auditing, fraud detection, or custom
/// OTP delivery mechanisms.
///
/// For the official Microsoft schema and field descriptions, see:
/// https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-email-otp-send-data
/// </remarks>
public sealed class EmailOtpSendEvent : EntraEvent<EmailOtpSendEventPayload>
{
    public override string Type => EntraEventTypes.EmailOtpSend;
}

/// <summary>
/// Payload for the EmailOtpSend event. Contains OTP delivery information
/// generated by Microsoft Entra, including the target identifier and the
/// one‑time code to be sent to the user.
///
/// This model reflects the structure of the JSON payload sent by Entra.
/// </summary>
/// <remarks>
/// Field meanings and behavior are defined by Microsoft.  
/// See the official documentation for details:
/// https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-email-otp-send-data
/// </remarks>
public sealed class EmailOtpSendEventPayload : EntraEventPayload
{
    public override string OdataType { get; } = EntraOdataTypes.EmailOtpSend.CalloutData;

    /// <summary>
    /// Contains the OTP delivery details, including the identifier
    /// (such as an email address) and the one‑time code generated
    /// by Microsoft Entra.
    /// </summary>
    /// <remarks>
    /// The <c>otpContext</c> object is always present for the
    /// EmailOtpSend event. It provides the data required for
    /// custom OTP delivery, logging, or security analysis.
    ///
    /// For details, see:
    /// https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-email-otp-send-data
    /// </remarks>
    [JsonPropertyName("otpContext")]
    public required OtpContext OtpContext { get; init; }
}