using Entra.EventHandlers.Abstractions.Protocol;
using System.Text.Json.Serialization;

namespace Entra.EventHandlers.Abstractions.Events;

/// <summary>
/// Represents the PasswordSubmit event sent by Microsoft Entra to a custom
/// extension endpoint during a just‑in‑time password migration flow.
///
/// This type provides a strongly typed model for the incoming JSON payload.
/// It mirrors the public contract defined by Microsoft and contains no
/// additional logic.
/// </summary>
/// <remarks>
/// The PasswordSubmit event is triggered when a user attempts to sign in
/// with a password that must be evaluated by a custom extension. Extensions
/// may use this event to migrate passwords, validate them, require a reset,
/// or block the authentication attempt.
///
/// For the official Microsoft schema and field descriptions, see:
/// https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-migrate-passwords-just-in-time
/// </remarks>
public sealed class PasswordSubmitEvent : EntraEvent<PasswordSubmitEventPayload>
{
    public override string Type => EntraEventTypes.PasswordSubmit;
}

/// <summary>
/// Payload for the PasswordSubmit event. Contains the encrypted password
/// context generated by Microsoft Entra, which the extension must decrypt
/// and evaluate according to the just‑in‑time password migration flow.
///
/// This model reflects the structure of the JSON payload sent by Entra.
/// </summary>
/// <remarks>
/// The <c>encryptedPasswordContext</c> contains the user’s submitted password
/// and a nonce, encrypted using the extension’s public key. Extensions must
/// decrypt this value to evaluate the password and must return the same nonce
/// in the response for verification purposes.
///
/// For detailed field definitions and processing guidance, see:
/// https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-migrate-passwords-just-in-time
/// </remarks>
public sealed class PasswordSubmitEventPayload : EntraEventPayload
{
    public override string OdataType { get; } = EntraOdataTypes.PasswordSubmit.CalloutData;

    /// <summary>
    /// The encrypted password context provided by Microsoft Entra. This value
    /// contains the submitted password and a nonce, encrypted with the
    /// extension’s public key. The extension must decrypt this value to
    /// evaluate the password and return the nonce in the response.
    /// </summary>
    [JsonPropertyName("encryptedPasswordContext")]
    public required string EncryptedPasswordContext { get; init; }
}