<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\Entra.EventHandlers.TestHelpers\Entra.EventHandlers.TestHelpers.csproj" />
    <ProjectReference Include="..\Entra.EventHandlers.Workforce\Entra.EventHandlers.Workforce.csproj" />
  </ItemGroup>

</Project>