<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<!-- NuGet metadata -->
	<PackageId>Entra.EventHandlers.Abstractions</PackageId>
	<Version>1.3.1</Version>
	<Authors>Jakub Szubarga</Authors>
	<Company>Szubarga.NET Jakub Szubarga</Company>
	<Description>Public abstractions and protocol definitions for Microsoft Entra External ID Authentication Event Handlers.</Description>
	<PackageTags>entra;entra-id;microsoft-entra;microsoft-entra-id;external-id;authentication-events;event-handlers;identity;authentication;dotnet;dotnet-library;csharp</PackageTags>
	
	<RepositoryUrl>https://github.com/szubajak/entra-event-handlers</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageProjectUrl>https://github.com/szubajak/entra-event-handlers</PackageProjectUrl>
	  
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageIcon>icon.png</PackageIcon>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  
	<PackageReleaseNotes>
	Initial public release of the Microsoft Entra External ID Authentication Event Handlers abstractions.
	Includes protocol models, action types, and directory attribute primitives.
	</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
	<None Include="LICENSE" Pack="true" PackagePath="" />
	<None Include="README.md" Pack="true" PackagePath="" />
	<None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
