<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
	<IsPackable>false</IsPackable>
	<ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\abstractions\Entra.EventHandlers.Abstractions\Entra.EventHandlers.Abstractions.csproj" />
  </ItemGroup>
	
</Project>
