<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
	<IsPackable>false</IsPackable>
	<ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
	<PackageReference Include="Entra.EventHandlers.Abstractions" Version="1.5.1" />
  </ItemGroup>
	
</Project>
