<Project Sdk="Microsoft.NET.Sdk.Web">
	
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputType>Library</OutputType>
	<IsPackable>true</IsPackable>
	<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>

	  <!-- NuGet metadata -->
	<PackageId>Entra.EventHandlers.AspNetCore</PackageId>
	<Version>1.0.5</Version>
	<Authors>Jakub Szubarga</Authors>
	<Company>Szubarga.NET Jakub Szubarga</Company>
	<Description>ASP.NET Core hosting adapter for Microsoft Entra External ID Authentication Event Handlers. Provides request/response adapters, endpoint base classes, DI integration, and minimal boilerplate for building production-ready authentication extensions.</Description>
	<PackageTags>entra;entra-id;microsoft-entra;microsoft-entra-id;external-id;authentication-events;event-handlers;identity;authentication;dotnet;aspnetcore;middleware;csharp</PackageTags>

	<RepositoryUrl>https://github.com/szubajak/entra-event-handlers</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageProjectUrl>https://github.com/szubajak/entra-event-handlers</PackageProjectUrl>

	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.NuGet.md</PackageReadmeFile>
	<PackageIcon>icon.png</PackageIcon>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>

	<PackageReleaseNotes>
	Initial public release of the ASP.NET Core hosting adapter for Microsoft Entra External ID Authentication Event Handlers.
	Includes request/response adapters, endpoint base classes, DI integration, and router endpoint.
	</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
	<None Include="LICENSE" Pack="true" PackagePath="" />
	<None Include="LICENSE-COMMERCIAL.md" Pack="true" PackagePath="" />
	<None Include="README.NuGet.md" Pack="true" PackagePath="" />
	<None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Entra.EventHandlers\Entra.EventHandlers.csproj" />
    <ProjectReference Include="..\..\hosting\Entra.EventHandlers.Hosting\Entra.EventHandlers.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Pack'">
	<PackageReference Include="Entra.EventHandlers" Version="1.2.10" PrivateAssets="all" />
  </ItemGroup>

</Project>
