using System.Text.Json.Serialization;

namespace Entra.EventHandlers.Abstractions.Protocol.Authentication;

/// <summary>
/// Represents the authentication context included in every Microsoft Entra
/// custom extension event. Contains correlation information, client details,
/// protocol metadata, and identity information relevant to the event.
/// </summary>
/// <remarks>
/// The authentication context is used for diagnostics, tracing, and making
/// decisions based on the client application, protocol, or user identity.
///
/// For details on the authentication context structure, see:
/// https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-overview
/// </remarks>
public class AuthenticationContext
{
    /// <summary>
    /// Gets or sets the correlation identifier associated with the event.
    /// This value is generated by Microsoft Entra and is useful for tracing
    /// and diagnostics across distributed systems.
    /// </summary>
    [JsonPropertyName("correlationId")]
    public Guid CorrelationId { get; init; }

    /// <summary>
    /// Gets or sets information about the client application that initiated
    /// the request, including IP address, locale, and market.
    /// </summary>
    [JsonPropertyName("client")]
    public ClientInfo? Client { get; init; }

    /// <summary>
    /// Gets or sets the authentication protocol used for the request
    /// (for example, <c>OAUTH2.0</c>).
    /// </summary>
    [JsonPropertyName("protocol")]
    public string? Protocol { get; init; }

    /// <summary>
    /// Gets or sets information about the client service principal associated
    /// with the request, if applicable.
    /// </summary>
    [JsonPropertyName("clientServicePrincipal")]
    public ServicePrincipalInfo? ClientServicePrincipal { get; init; }

    /// <summary>
    /// Gets or sets information about the resource service principal targeted
    /// by the request, if applicable.
    /// </summary>
    [JsonPropertyName("resourceServicePrincipal")]
    public ServicePrincipalInfo? ResourceServicePrincipal { get; init; }

    /// <summary>
    /// Gets or sets information about the user involved in the request,
    /// if the event is associated with a user identity.
    /// </summary>
    [JsonPropertyName("user")]
    public UserInfo? User { get; init; }
}