<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
	<OutputType>Exe</OutputType>
	<IsTestingPlatformApplication>true</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\Entra.EventHandlers.TestData\Entra.EventHandlers.TestData.csproj" />
    <ProjectReference Include="..\..\common\Entra.EventHandlers.TestHelpers\Entra.EventHandlers.TestHelpers.csproj" />
    <ProjectReference Include="..\..\hosting\Entra.EventHandlers.Hosting\Entra.EventHandlers.Hosting.csproj" />
    <ProjectReference Include="..\Entra.EventHandlers.AzureFunctions\Entra.EventHandlers.AzureFunctions.csproj" />
  </ItemGroup>

</Project>