<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<OutputType>Library</OutputType>
	<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="[7.2.0]" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\Entra.EventHandlers.TestHelpers\Entra.EventHandlers.TestHelpers.csproj" />
    <ProjectReference Include="..\..\core\Entra.EventHandlers.Workforce\Entra.EventHandlers.Workforce.csproj" />
    <ProjectReference Include="..\..\core\Entra.EventHandlers\Entra.EventHandlers.csproj" />
    <ProjectReference Include="..\..\hosting\Entra.EventHandlers.Hosting\Entra.EventHandlers.Hosting.csproj" />
    <ProjectReference Include="..\Entra.EventHandlers.AspNetCore.TestHost\Entra.EventHandlers.AspNetCore.TestHost.csproj" />
    <ProjectReference Include="..\Entra.EventHandlers.AspNetCore\Entra.EventHandlers.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>